/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface;

import java.awt.Image;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import applicationLogic.ClearingDonationBox;
import applicationLogicAccess.Access;
import applicationLogicAccess.CollectionAccess;

/**
 * 
 * @author Timo
 */
public class ClearDonationBox extends javax.swing.JDialog {
	int boxId;

	/**
	 * Initializes the Window
	 * 
	 * @param parent
	 *            the parent
	 * @param modal
	 *            determines if the window should be modal or not
	 * @param boxId
	 *            the ID of the DonationBox we want to use in this window
	 */
	public ClearDonationBox(java.awt.Frame parent, boolean modal, int boxId) {
		super(parent, modal);
		this.boxId = boxId;
		initComponents();
		this.setLocationRelativeTo(null);
		Date dt = new Date();
		dpClearing.setDate(dt);
		
		//added by sz
		Image imgIcon = new ImageIcon("images/icon.png").getImage();
		setIconImage(imgIcon);
		//
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code"> desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel10 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		dpClearing = new org.jdesktop.swingx.JXDatePicker();
		txtSum = new javax.swing.JFormattedTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		btnCancel = new javax.swing.JButton();
		btnAccept = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel10.setText("Spendendose leeren");

		jLabel1.setText("Entnommener Betrag*:");

		jLabel2.setText("Datum der Leerung:");

		txtSum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(
						new java.text.DecimalFormat("#0.00"))));

		jLabel3.setText("* Bitte \" , \" als Trennzeichen verwenden!");

		jLabel4.setText("   Beispiel: 127,89");

		btnCancel.setText("Abbrechen");
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		btnAccept.setText("Bestätigen");
		btnAccept.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAcceptActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(60, 60, 60)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(jLabel1))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		dpClearing,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addContainerGap(
																		132,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		txtSum,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		89,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(81, 81, 81)
								.addComponent(btnAccept)
								.addGap(77, 77, 77)
								.addComponent(btnCancel)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel4))
																.addGap(101,
																		101,
																		101))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel10,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		151,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(124,
																		124,
																		124)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel10)
								.addGap(26, 26, 26)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														dpClearing,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtSum,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addComponent(jLabel3)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel4)
								.addGap(42, 42, 42)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnCancel)
												.addComponent(btnAccept))
								.addContainerGap(33, Short.MAX_VALUE)));

		pack();
	}//</editor-fold>//GEN-END:initComponents

	private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
		if (dpClearing.getDate() != null) {
			try {
				String floatMe = txtSum.getText() + "f";
				floatMe = floatMe.replaceAll(",", ".");
				float sum = Float.parseFloat(floatMe);
				SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
				int choice = JOptionPane.showConfirmDialog(null,
						"Leerung mit folgenden Werten eintragen?\n\n "
								+ "Datum: " + sdf.format(dpClearing.getDate())
								+ "\nSumme: " + sum, "Leerung Bestätigen",
						JOptionPane.YES_NO_OPTION);
				if (choice == 0) {
					//                    Access.clearDonationBox(boxId,dpClearing.getDate(), sum);
					int collectionId = Access.getDonationBoxById(boxId)
							.getCollectionId(); //added bei sz
					Access.saveClearingDonationBox(new ClearingDonationBox(
							Access.dateToCalendar(dpClearing.getDate()), sum),
							collectionId, boxId); //added bei sz
					//                  CollectionAccess.calculateSum(boxId);
					CollectionAccess.calculateSumByCollectionId(collectionId);
					dispose();
					JOptionPane.showMessageDialog(
							null,
							"Die Leerung wurde mit folgenden Werten eingetragen:\n\n "
									+ "Datum: "
									+ sdf.format(dpClearing.getDate())
									+ "\nSumme: " + sum, "Erfolg",
							JOptionPane.PLAIN_MESSAGE);

				}
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(null,
						"Sie haben keinen gültigen Betrag eingegeben",
						"Fehler!", JOptionPane.ERROR_MESSAGE);
			} catch (SQLException ex) {
				JOptionPane.showMessageDialog(null, "SQLException", "Fehler!",
						JOptionPane.ERROR_MESSAGE);
			} catch (ParseException ex) {
				JOptionPane.showMessageDialog(null, "ParseException",
						"Fehler!", JOptionPane.ERROR_MESSAGE);
			}
		} else {
			JOptionPane.showMessageDialog(null,
					"Sie haben kein Datum eingegeben", "Fehler!",
					JOptionPane.ERROR_MESSAGE);
		}
	}//GEN-LAST:event_btnAcceptActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dispose();
	}//GEN-LAST:event_btnCancelActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger
					.getLogger(ClearDonationBox.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger
					.getLogger(ClearDonationBox.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger
					.getLogger(ClearDonationBox.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger
					.getLogger(ClearDonationBox.class.getName()).log(
							java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAccept;
	private javax.swing.JButton btnCancel;
	private org.jdesktop.swingx.JXDatePicker dpClearing;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JFormattedTextField txtSum;
	// End of variables declaration//GEN-END:variables
}
