/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface;

import java.awt.Image;

import javax.swing.ImageIcon;

import applicationLogic.OrganisationPerson;
import applicationLogicAccess.Access;

/**
 * 
 * @author Timo
 */
public class DetailsOrganisationPerson extends javax.swing.JDialog {
	int orgPersId;
	OrganisationPerson thisPers;

	/**
	 * Initializes the Window
	 * 
	 * @param parent
	 *            the parent
	 * @param modal
	 *            determines if the window should be modal or not
	 * @param orgPersId
	 *            the ID of the OrganisationPerson we want to display in this
	 *            window
	 */
	public DetailsOrganisationPerson(java.awt.Frame parent, boolean modal,
			int orgPersId) {
		super(parent, modal);
		this.orgPersId = orgPersId;
		thisPers = (OrganisationPerson) Access.getPersonById(orgPersId);
		initComponents();
		this.setLocationRelativeTo(null);
		txtId.setText("" + orgPersId);
		txtLastname.setText(thisPers.getLastName());
		txtForename.setText(thisPers.getForename());
		txtStreet.setText(thisPers.getAddress().getStreetName() + " "
				+ thisPers.getAddress().getHauseNumber());
		txtZipCity.setText(thisPers.getAddress().getZip() + " "
				+ thisPers.getAddress().getLocationName());
		txtEmail.setText(thisPers.getEmail());
		txtPhone.setText(thisPers.getTelephoneNumber());
		txtMobile.setText(thisPers.getMobilNumber());
		txtComment.setText(thisPers.getComment());
		//added by sz
		Image imgIcon = new ImageIcon("images/icon.png").getImage();
		setIconImage(imgIcon);
		//
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code"> desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel10 = new javax.swing.JLabel();
		txtComment = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		txtPhone = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtStreet = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtLastname = new javax.swing.JTextField();
		txtForename = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		txtEmail = new javax.swing.JTextField();
		txtZipCity = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		txtMobile = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		btnClose = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		txtId = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel10.setText("Detailansicht Organisationsmitglied");

		txtComment.setEditable(false);

		jLabel9.setText("Mobil");

		jLabel1.setText("Nachname");

		jLabel12.setText("Kommentar");

		txtPhone.setEditable(false);

		jLabel3.setText("Straße");

		txtStreet.setEditable(false);

		jLabel5.setText("Postleitzahl, Ort");

		txtLastname.setEditable(false);

		txtForename.setEditable(false);

		jLabel7.setText("Email");

		txtEmail.setEditable(false);

		txtZipCity.setEditable(false);

		jLabel8.setText("Festnetz");

		txtMobile.setEditable(false);

		jLabel2.setText("Vorname");

		btnClose.setText("Fenster schließen");
		btnClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCloseActionPerformed(evt);
			}
		});

		jLabel13.setText("ID");

		txtId.setEditable(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(32, 32, 32)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						jLabel7)
																				.addComponent(
																						jLabel8)
																				.addComponent(
																						jLabel9)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel12))
																.addGap(123,
																		123,
																		123)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						txtStreet,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						253,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										txtComment,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										253,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(
																										txtMobile,
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										253,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(
																										txtPhone,
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										253,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(
																										txtEmail,
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										253,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(
																										txtZipCity,
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										253,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										jLabel1,
																										javax.swing.GroupLayout.Alignment.TRAILING)
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel2)
																												.addGap(8,
																														8,
																														8)))
																				.addComponent(
																						jLabel13))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						txtForename,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						253,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						txtLastname,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						253,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						txtId,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						253,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(32, 32, 32))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel10)
																.addGap(137,
																		137,
																		137))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		btnClose)
																.addGap(199,
																		199,
																		199)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel10)
								.addGap(35, 35, 35)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel13)
												.addComponent(
														txtId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtLastname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														txtForename,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtStreet,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addGap(14, 14, 14)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtZipCity,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtEmail,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtPhone,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel8))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtMobile,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel9))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel12)
												.addComponent(
														txtComment,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18).addComponent(btnClose)
								.addContainerGap(23, Short.MAX_VALUE)));

		pack();
	}//</editor-fold>//GEN-END:initComponents

	private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
		dispose();
	}//GEN-LAST:event_btnCloseActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					DetailsOrganisationPerson.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					DetailsOrganisationPerson.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					DetailsOrganisationPerson.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					DetailsOrganisationPerson.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnClose;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField txtComment;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JTextField txtForename;
	private javax.swing.JTextField txtId;
	private javax.swing.JTextField txtLastname;
	private javax.swing.JTextField txtMobile;
	private javax.swing.JTextField txtPhone;
	private javax.swing.JTextField txtStreet;
	private javax.swing.JTextField txtZipCity;
	// End of variables declaration//GEN-END:variables
}
