/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

import applicationLogic.ClearingDonationBox;
import applicationLogic.DonationBox;
import applicationLogic.PersonHistory;
import applicationLogicAccess.Access;
import applicationLogicAccess.PersonHistoryAccess;

/**
 * 
 * @author Timo
 */
public class DetailsDonationBox extends javax.swing.JDialog {

	DefaultTableModel model;
	int boxId;
	private final int INVISIBLE_PERSON = 1000000;

	/**
	 * Initializes the Window
	 * 
	 * @param parent
	 *            the parent
	 * @param modal
	 *            determines if the window should be modal or not
	 * @param boxId
	 *            the ID of the Box we want to display in this window
	 */
	public DetailsDonationBox(java.awt.Frame parent, boolean modal, int boxId) {
		super(parent, modal);
		this.boxId = boxId;
		initComponents();
		this.setLocationRelativeTo(null);
		model = (DefaultTableModel) table.getModel();
		DonationBox box = Access.getDonationBoxById(boxId);
		lblId.setText("" + box.getBoxId());
		String status;
		if (box.getIsDeleted()) {
			status = "gelöscht";
		} else {
			status = box.getInUseForTable();
		}
		lblStatus.setText(status);

		String name;
		if (box.getCurrentResponsiblePerson().getPersonId() == INVISIBLE_PERSON) {
			name = " - ";
		} else {
			name = box.getCurrentResponsiblePerson().getLastName() + ", "
					+ box.getCurrentResponsiblePerson().getForename()
					+ " (ID: "
					+ box.getCurrentResponsiblePerson().getPersonId() + ")";
		}

		lblOrgPers.setText(name);

		if (box.getCollectionId() == 0) {
			lblCollection.setText("Keiner Sammlung zugeordnet");
		} else {
			lblCollection.setText(box.getCollectionId() + "");
		}
		lblComment.setText(box.getComment());
		ArrayList<ClearingDonationBox> list = box.getClearingDonationBoxes();
		SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
		String date = "---";
		float sum = 0.0f;
		for (ClearingDonationBox currClearing : list) {
			if (currClearing.getClearDate() != null) {
				date = sdf.format(currClearing.getClearDate().getTime());
			}
			sum += currClearing.getSum();
			model.insertRow(model.getRowCount(),
					new Object[] { currClearing.getClearingId(), date,
							currClearing.getSum() });
		}
		txtSum.setText("" + sum);
		
		//added by sz
		Image imgIcon = new ImageIcon("images/icon.png").getImage();
		setIconImage(imgIcon);
		//
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code"> desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel8 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		lblComment = new javax.swing.JTextField();
		lblCollection = new javax.swing.JTextField();
		lblOrgPers = new javax.swing.JTextField();
		lblId = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		lblStatus = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		btnClose = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		txtSum = new javax.swing.JFormattedTextField();
		ImageIcon imgAuge = new ImageIcon("images/imgAuge.png");
		btnOrgPersHistory = new javax.swing.JButton();
		btnOrgPersHistory.setIcon(imgAuge);

		jLabel8.setText("Bisherige Leerungen");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Detailansicht Spendenbox");
		setResizable(false);

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel10.setText("Detailansicht Spendenbox");

		jLabel3.setText("Zugeordnete Sammlung");

		jLabel2.setText("Verantwortliche Person");

		jLabel1.setText("ID");

		lblComment.setEditable(false);

		lblCollection.setEditable(false);

		lblOrgPers.setEditable(false);

		lblId.setEditable(false);

		jLabel4.setText("Kommentar");

		jLabel5.setText("Status");

		lblStatus.setEditable(false);

		jLabel6.setText("Gesamtbetrag");

		jLabel7.setText("Bisherige Leerungen");

		btnClose.setText("Fenster schließen");
		btnClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCloseActionPerformed(evt);
			}
		});

		table.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "ID", "Datum", "Betrag" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane2.setViewportView(table);

		txtSum.setEditable(false);
		txtSum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
				new javax.swing.text.NumberFormatter(java.text.NumberFormat
						.getCurrencyInstance())));

		btnOrgPersHistory.setText("Historie");
		btnOrgPersHistory
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						btnOrgPersHistoryActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(0, 1, Short.MAX_VALUE)
								.addComponent(btnClose).addGap(410, 410, 410))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(15, 15, 15)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6)
												.addComponent(jLabel4)
												.addComponent(jLabel3)
												.addComponent(jLabel2)
												.addComponent(jLabel5)
												.addComponent(jLabel1)
												.addComponent(jLabel7))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(16, 16,
																		16)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						lblStatus)
																				.addComponent(
																						lblId)
																				.addComponent(
																						lblComment)
																				.addComponent(
																						lblCollection)
																				.addComponent(
																						txtSum)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel10)
																								.addGap(0,
																										0,
																										Short.MAX_VALUE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										lblOrgPers)
																								.addGap(15,
																										15,
																										15)
																								.addComponent(
																										btnOrgPersHistory))))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		jScrollPane2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		379,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(15, 15, 15)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel10)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														lblId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														lblStatus,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														lblOrgPers,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2)
												.addComponent(btnOrgPersHistory))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														lblCollection,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														lblComment,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														txtSum,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel7)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														299,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										60, Short.MAX_VALUE)
								.addComponent(btnClose).addGap(25, 25, 25)));

		pack();
	}//</editor-fold>//GEN-END:initComponents

	private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
		dispose();
	}//GEN-LAST:event_btnCloseActionPerformed

	private void btnOrgPersHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgPersHistoryActionPerformed
		ArrayList<PersonHistory> list = PersonHistoryAccess
				.searchOrgaBoxHistoriesByCollectionId(boxId);
		HistoryPerson mainFrame = new HistoryPerson(null, true, list);
		mainFrame.setVisible(true);
	}//GEN-LAST:event_btnOrgPersHistoryActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					DetailsDonationBox.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					DetailsDonationBox.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					DetailsDonationBox.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					DetailsDonationBox.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		//        java.awt.EventQueue.invokeLater(new Runnable() {
		//            public void run() {
		//                DetailsDonationBox dialog = new DetailsDonationBox(new javax.swing.JFrame(), true);
		//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		//                    @Override
		//                    public void windowClosing(java.awt.event.WindowEvent e) {
		//                        System.exit(0);
		//                    }
		//                });
		//                dialog.setVisible(true);
		//            }
		//        });
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnClose;
	private javax.swing.JButton btnOrgPersHistory;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField lblCollection;
	private javax.swing.JTextField lblComment;
	private javax.swing.JTextField lblId;
	private javax.swing.JTextField lblOrgPers;
	private javax.swing.JTextField lblStatus;
	private javax.swing.JTable table;
	private javax.swing.JFormattedTextField txtSum;
	// End of variables declaration//GEN-END:variables
}
