/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface;

import java.awt.Image;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import applicationLogic.DonationCollection;
import applicationLogic.OrganisationPerson;
import applicationLogicAccess.Access;
import applicationLogicAccess.CollectionAccess;

/**
 * 
 * @author Timo
 */
public class SearchDonationBoxes extends javax.swing.JDialog {
	ArrayList<OrganisationPerson> orgPersList;
	ArrayList<DonationCollection> collList;
	String[] orgPersArray;
	String[] collArray;

	/**
	 * Initializes the Window
	 * 
	 * @param parent
	 *            the parent
	 * @param modal
	 *            determines if the window should be modal or not
	 */
	public SearchDonationBoxes(java.awt.Frame parent, boolean modal) {
		super(parent, modal);

		/*
		 * model code for filling Jcombobox use COMBOBOXNAME.setModel(new
		 * javax.swing.DefaultComboBoxModel(ARRAYNAME)); after initcomponents();
		 * declare the Array for the class
		 */
		orgPersList = Access.getAllOrganisationPersons();
		int sizePersList = orgPersList.size();
		orgPersArray = new String[sizePersList];
		int i = 0;
		for (OrganisationPerson currPers : orgPersList) {
			String currString = "" + currPers.getPersonId() + " "
					+ currPers.getLastName() + ", " + currPers.getForename();
			orgPersArray[i] = currString;
			i++;
		}
		// end of model code !dont forget setmodel!!
		try {
			collList = CollectionAccess.getAllDonationCollections();
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(null, "Datenbankfehler!", "Fehler!",
					JOptionPane.ERROR_MESSAGE);
		} catch (ParseException ex) {
			JOptionPane.showMessageDialog(null, "Datenbankfehler!", "Fehler!",
					JOptionPane.ERROR_MESSAGE);
		}
		int sizeCollList = collList.size();
		collArray = new String[sizeCollList];
		i = 0;
		for (DonationCollection currColl : collList) {
			String currString = "" + currColl.getCollectionId();
			collArray[i] = currString;
			i++;
		}
		initComponents();
		ImageIcon imgLupe = new ImageIcon("images/imgLupe.png");
		ImageIcon imgAuge = new ImageIcon("images/imgAuge.png");
		ImageIcon imgPerson = new ImageIcon("images/imgPerson.png");
		ImageIcon imgPlus = new ImageIcon("images/imgPlus.png");
		ImageIcon imgBearbeiten = new ImageIcon("images/imgBearbeiten.png");
		ImageIcon imgPfeil = new ImageIcon("images/imgPfeil.png");
		ImageIcon imgKreuz = new ImageIcon("images/imgKreuz.png");
		ImageIcon imgDocument = new ImageIcon("images/imgDocument.png");
		ImageIcon imgGeld = new ImageIcon("images/imgGeld.png");
		//added by sz
		Image imgIcon = new ImageIcon("images/icon.png").getImage();
		setIconImage(imgIcon);
		//
		btnCancel.setIcon(imgKreuz);
		btnSearch.setIcon(imgLupe);

		this.setLocationRelativeTo(null);
		comBoxPerson
				.setModel(new javax.swing.DefaultComboBoxModel(orgPersArray));
		comBoxCollection.setModel(new javax.swing.DefaultComboBoxModel(
				collArray));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	// <editor-fold defaultstate="collapsed" desc="Generated Code"> desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel10 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		btnSearch = new javax.swing.JButton();
		btnCancel = new javax.swing.JButton();
		txtFieldId = new javax.swing.JTextField();
		txtFieldComment = new javax.swing.JTextField();
		chkBoxInUseYes = new javax.swing.JCheckBox();
		chkBoxInUseNo = new javax.swing.JCheckBox();
		datePickerCleared = new org.jdesktop.swingx.JXDatePicker();
		chkBoxId = new javax.swing.JCheckBox();
		chkBoxPerson = new javax.swing.JCheckBox();
		chkBoxComment = new javax.swing.JCheckBox();
		chkBoxCollection = new javax.swing.JCheckBox();
		chkBoxCleared = new javax.swing.JCheckBox();
		chkBoxInUse = new javax.swing.JCheckBox();
		comBoxPerson = new javax.swing.JComboBox();
		comBoxCollection = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Suchen");
		setResizable(false);

		jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel10.setText("Spendenbox(en) suchen");

		jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel9.setText("Suche nach:");

		btnSearch.setText("Suchen");
		btnSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSearchActionPerformed(evt);
			}
		});

		btnCancel.setText("Abbrechen");
		btnCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnCancelActionPerformed(evt);
			}
		});

		chkBoxInUseYes.setText("JA");

		chkBoxInUseNo.setText("Nein");

		datePickerCleared.setName(""); // NOI18N

		chkBoxId.setText("ID");

		chkBoxPerson.setText("Verantwortliche Person");

		chkBoxComment.setText("Kommentar");

		chkBoxCollection.setText("Zugeordnete Sammlung");

		chkBoxCleared.setText("Geleert am");

		chkBoxInUse.setText("In Benutzung");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		chkBoxCleared)
																.addGap(0,
																		0,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel9)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																																.addComponent(
																																		chkBoxCollection)
																																.addGroup(
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		layout.createSequentialGroup()
																																				.addComponent(
																																						chkBoxInUse)
																																				.addGap(50,
																																						50,
																																						50)))
																												.addComponent(
																														chkBoxId)
																												.addComponent(
																														chkBoxPerson)
																												.addComponent(
																														chkBoxComment))
																								.addGap(31,
																										31,
																										31)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		chkBoxInUseYes)
																																.addGap(18,
																																		18,
																																		18)
																																.addComponent(
																																		chkBoxInUseNo))
																												.addComponent(
																														txtFieldId,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														224,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														txtFieldComment,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														224,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														comBoxPerson,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														140,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																																.addComponent(
																																		comBoxCollection,
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		0,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		Short.MAX_VALUE)
																																.addComponent(
																																		datePickerCleared,
																																		javax.swing.GroupLayout.Alignment.LEADING,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		140,
																																		Short.MAX_VALUE)))))
																.addGap(18, 18,
																		18))))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(117, 117, 117)
								.addComponent(jLabel10)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(95, 95, 95)
								.addComponent(btnSearch,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										110,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(btnCancel).addGap(95, 95, 95)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(21, 21, 21)
								.addComponent(jLabel10)
								.addGap(18, 18, 18)
								.addComponent(jLabel9)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						chkBoxId)
																				.addComponent(
																						txtFieldId,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(38, 38,
																		38))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		chkBoxPerson)
																.addComponent(
																		comBoxPerson,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(chkBoxComment)
												.addComponent(
														txtFieldComment,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(chkBoxCollection)
												.addComponent(
														comBoxCollection,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(chkBoxCleared)
												.addComponent(
														datePickerCleared,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(chkBoxInUse)
												.addComponent(chkBoxInUseYes)
												.addComponent(chkBoxInUseNo))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										29, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnSearch)
												.addComponent(btnCancel))
								.addGap(40, 40, 40)));

		pack();
	}//</editor-fold>//GEN-END:initComponents

	/**
	 * @author Timo
	 * 
	 * @param evt
	 */
	private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
		int boxId = -1;
		int responsiblePersonId = -1;
		String comment = null;
		int collectionId = -1;
		Date date = null;
		boolean inUseYes = true;
		boolean inUseNo = true;

		if (chkBoxId.isSelected()) {
			boxId = Integer.parseInt(txtFieldId.getText());
		}

		if (chkBoxPerson.isSelected() && comBoxPerson.getItemCount() > 0) {
			String currSelectedPerson = (String) comBoxPerson.getSelectedItem();
			String[] splitted = currSelectedPerson.split(" ");
			responsiblePersonId = Integer.parseInt(splitted[0]);
		}

		if (chkBoxComment.isSelected()) {
			comment = txtFieldComment.getText();
		}

		if (chkBoxCollection.isSelected()
				&& comBoxCollection.getItemCount() > 0) {
			collectionId = Integer.parseInt((String) comBoxCollection
					.getSelectedItem());
		}

		if (chkBoxCleared.isSelected()) {
			date = datePickerCleared.getDate();
		}

		if (chkBoxInUse.isSelected()) {
			inUseYes = chkBoxInUseYes.isSelected();
			inUseNo = chkBoxInUseNo.isSelected();
		}

		Access.setTempDonationBoxes(Access.searchDonationBox(boxId,
				responsiblePersonId, comment, collectionId, date, inUseYes,
				inUseNo));
		dispose();
	}//GEN-LAST:event_btnSearchActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		dispose();
	}//GEN-LAST:event_btnCancelActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc="Generated Code">
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					SearchDonationBoxes.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					SearchDonationBoxes.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					SearchDonationBoxes.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					SearchDonationBoxes.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCancel;
	private javax.swing.JButton btnSearch;
	private javax.swing.JCheckBox chkBoxCleared;
	private javax.swing.JCheckBox chkBoxCollection;
	private javax.swing.JCheckBox chkBoxComment;
	private javax.swing.JCheckBox chkBoxId;
	private javax.swing.JCheckBox chkBoxInUse;
	private javax.swing.JCheckBox chkBoxInUseNo;
	private javax.swing.JCheckBox chkBoxInUseYes;
	private javax.swing.JCheckBox chkBoxPerson;
	private javax.swing.JComboBox comBoxCollection;
	private javax.swing.JComboBox comBoxPerson;
	private org.jdesktop.swingx.JXDatePicker datePickerCleared;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField txtFieldComment;
	private javax.swing.JTextField txtFieldId;
	// End of variables declaration//GEN-END:variables
}
